### ISSUE TITLE
Review Ivan

### ISSUE THREAD

**Issue by ivanunksov** [teokem/project-work-2020-elskorda#1]
Hi Eleni! The project is well-documented and reproducible. Just a few improvement suggestions:
1)	’First case 1’ figure: 2 panels of your graph are close to each other, and y-label in the right panel is overlapping with the left panel. Could you fix that?
2)	3D plot in ‘How can we evaluate our pseudo random generator?’ section: you say ‘try to rotate it’ but I can’t. Or that’s only my issue?
3)	Requirements ask for ‘the figures are saved as rasterized images (300 dpi) or vector art’.
4)	Also from requirements: please include ‘a brief explanation of the reason each package/library was used’.
5)	Given that it's a project for teaching, I'd like to point out that there’re a number of small typos in markdowns: e.g. ’facinating’, ’how school’, ’precice’ etc.
6)	Did you create a DOI?
Cheers,
Ivan

**Comment by elskorda** [comment]
Hi Ivan ,
Thank you for your very  useful feedback !!
comments 1, 3,4, 5 and 6 are addressed . For comment 2 : you will not be able to rotate if you run everything using the Run button in the notebook you really need to run each sell individually as I wrote in the instructions. At least that was the case for me: when I rerun the notebook all together the figures appear static.
